Updating judgment uri sets collection based off new uri
nationalarchives/ds-caselaw-editor-ui pull request #1017
Opened 2023-06-29 16:24 UTC by anthonyhashemi

## Changes in this PR:

- Update marklogic api client to 11.0.0 https://github.com/nationalarchives/ds-caselaw-custom-api-client/releases/tag/v11.0.0 to make use of the updated and renamed `copy_document` method so that it sets the collection of the new document based off the uri, so that we dont get floating documents which were at a /failure/ uri since the parser failed to pick up an ncn which existed in the document and then got updated to a real ncn uri by an editor.

## Trello card / Rollbar error (etc)

https://trello.com/c/0Q5fI6gA/1072-ingesting-uri-parse-failures-not-being-added-to-judgment-or-press-summary-collection

2023-06-29 16:34 UTC, dragon-dxw commented
> Note: the reason failure uris show in judgment collection is that we default to anything without press-summary in the uri to be in the judgment collection for now.

This gave me a fright but it's fine -- they won't be *published* judgments.

2023-06-29 16:37 UTC, dragon-dxw commented
ds-caselaw-editor-ui/judgments/tests/utils/test_utils.py also refers to copy_judgment (hence the failing tests)

2023-06-29 16:37 UTC, dragon-dxw requested changes
ds-caselaw-editor-ui/judgments/tests/utils/test_utils.py also refers to copy_judgment (hence the failing tests)

2023-06-29 16:38 UTC, anthonyhashemi commented
> > Note: the reason failure uris show in judgment collection is that we default to anything without press-summary in the uri to be in the judgment collection for now.
> 
> This gave me a fright but it's fine -- they won't be _published_ judgments.

Yep exactly! I have a ticket to look into passing the info of judgment vs press summary outside ncn from the parser so that we can distinguish them for when we want to separate out the editor ui, but for now its not particularly an issue

2023-06-29 16:39 UTC, anthonyhashemi commented
> test_utils

Cheers

2023-06-29 16:45 UTC, anthonyhashemi commented
> ds-caselaw-editor-ui/judgments/tests/utils/test_utils.py also refers to copy_judgment (hence the failing tests)

Have updated along with some more name updates, but havent touched `judgments/views/judgment_edit.py` as I know @jacksonj04 's  work is touching all of that flow.

2023-06-30 10:36 UTC, dragon-dxw approved these changes

2023-06-30 10:55 UTC, merged