Added status and type label to EUI
nationalarchives/ds-caselaw-editor-ui pull request #1067
Opened 2023-07-12 11:35 UTC by Donna-H

## Changes in this PR:
Added status and type label as per design here https://xsodca.axshare.com/?id=ae2k60&p=metadata-panel-with-status-and-type&c=1 some backend required BE placeholder after Type label see images below card has been created for BE.

## Trello card / Rollbar error (etc)
https://trello.com/c/ucQ9ia8u/1134-eui-add-judgment-status-and-doc-type-label-into-metadata-panel-fe-dev
## Screenshots of UI changes:

### Before
![before](https://github.com/nationalarchives/ds-caselaw-editor-ui/assets/75584408/72e64dbb-bcb1-4a95-9021-c683c2f77e0d)

### After
Judgment
![judgment-view](https://github.com/nationalarchives/ds-caselaw-editor-ui/assets/75584408/f9534cf0-20e0-4891-9443-f66ee7f19a63)

Press Summary
![press-summary-view](https://github.com/nationalarchives/ds-caselaw-editor-ui/assets/75584408/9a717b34-48e7-4008-aede-2adaed665e62)

- [ ] Requires env variable(s) to be updated

2023-07-12 11:35 UTC, Donna-H commented
![](https://github.trello.services/images/mini-trello-icon.png) [EUI - Add judgment status and doc type label into metadata panel [FE DEV]](https://trello.com/c/ucQ9ia8u/1134-eui-add-judgment-status-and-doc-type-label-into-metadata-panel-fe-dev)

2023-07-12 12:01 UTC, anthonyhashemi commented on ds_caselaw_editor_ui/templates/includes/judgment/metadata_panel_form.html
> +            <p>Judgment or Press Summary BE</p>
for the backend portion we plan on adding a `document_type` property to the Judgment / Press summary / Document object.

So if you want to prepare for that you can update the template to read in from a context variable, say `{{ document_type }}` here, which will be defined by `judgment.document_type` in the view. 

Then once we have updated the apiclient and released a new version, you will just have to update the EUI to use the new version in this PR.

In the meantime, if you dont want to be completely blocked and get your PR in for now, you could always utilise the same logic we did in the PUI:


```
    press_summary_suffix = "/press-summary/1"
    if document_uri.endswith(press_summary_suffix):
        context["document_type"] = "press_summary"
    else:
        context["document_type"] = "judgment"
```

from `judgments/views/detail.py` in the PUI.

2023-07-12 12:14 UTC, Donna-H commented on ds_caselaw_editor_ui/templates/includes/judgment/metadata_panel_form.html
> +            <p>Judgment or Press Summary BE</p>
@anthonyhashemi updated`{{ judgment.document_type }}` have other FE in the 'To Do' working on these now. So this PR can remain in blocked once BE have updated the apiclient and released a new version,  new card for updating the EUI to use the new version in this PR.

2023-07-12 14:12 UTC, timcowlishaw requested changes
Looks great to me Donna! one very minor visual nitpick - would it be possible to take a quick look at what's going on with the spacing between the TDR Ref, status and document type? it looks like there's about half as much space between the first two as the second, and the "status" label doesn't quite line up vertically with the actual status.

Thank you!

![252953813-9a717b34-48e7-4008-aede-2adaed665e62](https://github.com/nationalarchives/ds-caselaw-editor-ui/assets/4279/ddb5f619-7d0a-4d4f-bb76-67ccd9e698e4)

2023-07-12 14:12 UTC, timcowlishaw commented on ds_caselaw_editor_ui/sass/includes/_metadata.scss
>    &__ncn {
One for the refactoring column rather than a thing to do now, but it might be nice to refactor here to use Flexbox or grid, so we don't have to approximate and hardcode these percentages

2023-07-14 14:37 UTC, timcowlishaw commented
> Looks great to me Donna! one very minor visual nitpick - would it be possible to take a quick look at what's going on with the spacing between the TDR Ref, status and document type? it looks like there's about half as much space between the first two as the second, and the "status" label doesn't quite line up vertically with the actual status.
> 
> Thank you!
> 
> ![252953813-9a717b34-48e7-4008-aede-2adaed665e62](https://user-images.githubusercontent.com/4279/252998982-ddb5f619-7d0a-4d4f-bb76-67ccd9e698e4.png)


Aha Donna, don't worry about this - I'm doing a bit of refactoring and reckon it'll be easier to look at at the same time! If it's ok with you i'll add a couple of tweaks to this branch myself before we merge.

2023-07-14 15:43 UTC, timcowlishaw commented
@Donna-H I've pushed a couple of tweaks, I hope you don't mind - I'll go through them with you when you're back before merging!

2023-07-17 14:13 UTC, timcowlishaw approved these changes

2023-07-17 14:49 UTC, anthonyhashemi commented on ds_caselaw_editor_ui/templates/includes/judgment/metadata_panel_form.html
> +            <p>Judgment or Press Summary BE</p>
The actual judgment property might be slightly different, but once @jacksonj04 has done that work we can update this appropriately

2023-07-17 14:54 UTC, merged