Tidy up the sidebar, add link to related docs
nationalarchives/ds-caselaw-editor-ui pull request #1089
Opened 2023-07-26 16:47 UTC by timcowlishaw

## Changes in this PR:

This does a few things

- add a link to related documents in the editor sidebar
- refresh the visual design of the sidebar per terry's latest designs
- refactor the logic for identifying document type and related document in order to reduce repetition

## Trello card / Rollbar error (etc)

https://trello.com/c/PfJOSaeH/1202-eui-ps-add-a-link-to-the-associated-document-on-the-side-panel-for-publish-and-put-on-hold-screens

## Screenshots of UI changes:

### Before
<img width="322" alt="Screenshot 2023-07-26 at 18 45 36" src="https://github.com/nationalarchives/ds-caselaw-editor-ui/assets/4279/f747b1ff-1f31-44bb-b2ab-a8dff997371a">

### After

<img width="322" alt="Screenshot 2023-07-26 at 18 41 35" src="https://github.com/nationalarchives/ds-caselaw-editor-ui/assets/4279/70a130d7-de9f-4899-8c28-f582ff514291">

2023-07-26 16:48 UTC, timcowlishaw commented
![](https://github.trello.services/images/mini-trello-icon.png) [EUI: PS - add a link to the associated document on the side panel for 'publish and 'put on-hold' screens.](https://trello.com/c/PfJOSaeH/1202-eui-ps-add-a-link-to-the-associated-document-on-the-side-panel-for-publish-and-put-on-hold-screens)

2023-07-27 13:55 UTC, Terry-Price requested changes
Looks a whole lot better @timcowlishaw 
Was just wondering two small things that might help:

- Could the bold headings line height match the link line height so the clusters were uniform line height. might make it visually simpler.
- Was wondering about the word 'problem' could it be 'issue' as this is seen as surmountable  and a little softer business language.

2023-07-27 14:24 UTC, timcowlishaw commented
hey @Terry-Price aha no probs - how's this? That copy change was already done, i just forgot to do `compilemessages` before taking the screenshot!
<img width="322" alt="Screenshot 2023-07-27 at 16 23 08" src="https://github.com/nationalarchives/ds-caselaw-editor-ui/assets/4279/d7327009-d0de-4e1d-9c37-d0c9d2e77fed">

2023-07-31 10:49 UTC, jacksonj04 requested changes
There's a whole bunch of test changes you can avoid by swapping to an already-existing API function over writing your own document existence check.

2023-07-31 10:49 UTC, jacksonj04 commented on judgments/utils/__init__.py
> +def check_document_at_uri_exists(document_uri: str) -> Optional[str]:
There's already a function in the API client for this; `MarklogicApiClient.document_exists(str: uri)` will give you a boolean for if there's a document at the given URI.

2023-07-31 11:18 UTC, anthonyhashemi commented on judgments/utils/__init__.py
> +def set_document_type_and_link(
You can now update EUI to use apiclient 13.0.0 or above to determine the document type from the document_uri.

2023-07-31 11:18 UTC, anthonyhashemi commented on judgments/utils/__init__.py
> +def set_document_type_and_link(
ah I see Nick already beat me to that comment

2023-07-31 13:48 UTC, timcowlishaw commented on judgments/utils/__init__.py
> +def check_document_at_uri_exists(document_uri: str) -> Optional[str]:
aha ace, thank you Nick!

2023-07-31 13:49 UTC, timcowlishaw commented on judgments/utils/__init__.py
> +def set_document_type_and_link(
perfect, that simplifies things considerably!

2023-08-02 15:26 UTC, dragon-dxw approved these changes

2023-08-03 10:10 UTC, Terry-Price approved these changes
Spiffingly good.

2023-08-03 10:30 UTC, jacksonj04 approved these changes

2023-08-03 10:34 UTC, merged