update metadata panel review page for press summaries
nationalarchives/ds-caselaw-editor-ui pull request #1091
Opened 2023-07-31 12:20 UTC by Donna-H

## Changes in this PR:
update metadata panel review page press summaries as designed https://ct3ku9.axshare.com/?id=8sulyn&p=ps-review-showing_metadata-panel_mvp_static&c=1
## Trello card / Rollbar error (etc)
https://trello.com/c/qfPQTUIB/1193-3-eui-mvp-frontend-for-metadata-press-summary
## Screenshots of UI changes:

### Before
![before](https://github.com/nationalarchives/ds-caselaw-editor-ui/assets/75584408/14c808b0-1c62-4c3d-9215-d2a8f6db9d4a)

### After
![after](https://github.com/nationalarchives/ds-caselaw-editor-ui/assets/75584408/4754140c-c335-4e06-8bf5-e2a780573272)

- [ ] Requires env variable(s) to be updated

2023-07-31 12:20 UTC, Donna-H commented
![](https://github.trello.services/images/mini-trello-icon.png) [3. EUI: MVP Frontend for metadata Press summary](https://trello.com/c/qfPQTUIB/1193-3-eui-mvp-frontend-for-metadata-press-summary)

2023-07-31 13:05 UTC, anthonyhashemi commented on locale/en_GB/LC_MESSAGES/django.po
> +# SOME DESCRIPTIVE TITLE.judgment
whats this line about?

2023-07-31 13:06 UTC, anthonyhashemi commented on locale/en_GB/LC_MESSAGES/django.po
> +msgid "judgment.publication_date"
I think `document.publication_date` is better since its not just for judgments

2023-07-31 13:08 UTC, anthonyhashemi commented on ds_caselaw_editor_ui/templates/includes/judgment/metadata_panel_static.html
> +            <span class="judgment-metadata-panel__value">{{ judgment.neutral_citation }}</span>
not for this PR but we should refactor the view to refer to `document` and not `judgment` since it can be a press summary sometimes

2023-07-31 13:14 UTC, Donna-H commented on locale/en_GB/LC_MESSAGES/django.po
> +msgid "judgment.publication_date"
@anthonyhashemi updated

2023-07-31 13:15 UTC, Donna-H commented on locale/en_GB/LC_MESSAGES/django.po
> +# SOME DESCRIPTIVE TITLE.judgment
@anthonyhashemi not sure why it was there deleted

2023-07-31 13:38 UTC, timcowlishaw requested changes

2023-07-31 13:38 UTC, timcowlishaw commented on ds_caselaw_editor_ui/templates/includes/judgment/metadata_panel_static.html
> +        {% if document_type == "judgment" %}
Hey Donna, I think i'd favour keeping this panel as similar as possible for each of the two types of document, instead of doing the test for the type of document out here, we could do it within the `"judgment-metadata-panel__key" sections that differ between the two, eg to choose between "Judgment date" and "Publication date" - that way we cut down on duplication!

2023-07-31 13:38 UTC, timcowlishaw commented on ds_caselaw_editor_ui/templates/judgment/full_text_html.html
> +  {% if document_type == "judgment" %}
Perfect, only tiny thing is that we need to do this in `full_text_pdf.html` also!

2023-07-31 15:00 UTC, Donna-H commented on ds_caselaw_editor_ui/templates/includes/judgment/metadata_panel_static.html
> +        {% if document_type == "judgment" %}
@timcowlishaw okay it is all updated

2023-07-31 15:00 UTC, Donna-H commented on ds_caselaw_editor_ui/templates/judgment/full_text_html.html
> +  {% if document_type == "judgment" %}
oops !

2023-07-31 17:28 UTC, timcowlishaw approved these changes

2023-07-31 17:28 UTC, timcowlishaw commented
Great stuff Donna!

2023-08-01 08:47 UTC, jacksonj04 requested changes
A couple of smol optimising changes, but looking good!

2023-08-01 08:47 UTC, jacksonj04 commented on locale/en_GB/LC_MESSAGES/django.po
> +msgid "judgment.document.type"
We should probably lose the excess `judgment.` here.

```suggestion
msgid "document.type"
```

2023-08-01 08:47 UTC, jacksonj04 commented on ds_caselaw_editor_ui/templates/includes/judgment/metadata_panel_static.html
> +        {% if document_type == "judgment" %}
You don't need to make this conditional; you can use `{{ judgment.document_noun|capfirst }}` to automatically get the right words to describe the document type and then capitalise it correctly.

2023-08-01 09:06 UTC, Donna-H commented on ds_caselaw_editor_ui/templates/includes/judgment/metadata_panel_static.html
> +        {% if document_type == "judgment" %}
@jacksonj04 okay I tried this initially and it would not work so please pull the branch and update it thank you

2023-08-03 10:11 UTC, timcowlishaw commented
Folks i'm going to take this over, and rebase on top of the new API client branch if that's ok! @Donna-H @jacksonj04

2023-08-03 10:31 UTC, jacksonj04 approved these changes

2023-08-03 10:43 UTC, merged