Restyle of unlock page - made to look similar to unlock, publish interactions
nationalarchives/ds-caselaw-editor-ui pull request #1265
Opened 2023-11-08 15:03 UTC by Donna-H

## Changes in this PR:
Restyle of unlock page - made to look similar to unlock, publish interactions
## Trello card / Rollbar error (etc)
https://trello.com/c/6SUqtJGI/1444-eui-design-review
## Screenshots of UI changes:

### Before
![before-redesgn](https://github.com/nationalarchives/ds-caselaw-editor-ui/assets/75584408/c0554761-d78c-44f7-a128-283a2f65042f)

### After
![after-redesign](https://github.com/nationalarchives/ds-caselaw-editor-ui/assets/75584408/665454ce-4f00-4b1a-8c8a-579596897701)

- [ ] Requires env variable(s) to be updated

2023-11-08 15:08 UTC, Donna-H commented
![](https://github.trello.services/images/mini-trello-icon.png) [[EUI] Design Review](https://trello.com/c/6SUqtJGI/1444-eui-design-review)

2023-11-08 15:08 UTC, Donna-H commented
![](https://github.trello.services/images/mini-trello-icon.png) [[EUI] Design Review](https://trello.com/c/6SUqtJGI/1444-eui-design-review)

2023-11-09 10:31 UTC, jacksonj04 requested changes

2023-11-09 10:31 UTC, jacksonj04 commented on ds_caselaw_editor_ui/sass/includes/_judgment_unlock.scss
> +.judgment-unlock {
This feels like something which is too specific (ie there's no reason for the unlock page to have its own clsses here); could we make an existing class more generic and deduplicate the rest?

2023-11-09 10:40 UTC, Donna-H commented on ds_caselaw_editor_ui/sass/includes/_judgment_unlock.scss
> +.judgment-unlock {
@jacksonj04 I kept this class from when page was originally created just  reordered the name put judgement first .  The other interactions this is similar to on hold and publish use the class judgment-component so can be changed to that instead and delete the style sheet  judgment_unlock.scss add all styling to the judgment_component.scss which is also used by metadata_panel_static.html and judgment_with-sidebar.html @timcowlishaw any thought on this to change ?

2023-11-09 13:33 UTC, jacksonj04 commented on ds_caselaw_editor_ui/sass/includes/_judgment_unlock.scss
> +.judgment-unlock {
That would be my favourite, there's no reason for the unlock page to have any of its own styling.

2023-11-09 16:06 UTC, Donna-H commented on ds_caselaw_editor_ui/sass/includes/_judgment_unlock.scss
> +.judgment-unlock {
@jacksonj04 updated and screenshots updated too

2023-11-09 16:42 UTC, jacksonj04 approved these changes
LGTM! :shipit:

2023-11-09 16:46 UTC, merged