Increase minimum password length to 15
nationalarchives/ds-caselaw-editor-ui pull request #1478
Opened 2024-06-20 15:19 UTC by dragon-dxw

new: <img width="574" alt="image" src="https://github.com/nationalarchives/ds-caselaw-editor-ui/assets/85497046/05c9ce20-6ad0-4b3c-90a2-cb127e1c2e33">

2024-06-20 15:24 UTC, adam-murray approved these changes

2024-06-20 15:57 UTC, rjw1 requested changes
Policy is 16.

2024-06-20 16:41 UTC, dragon-dxw commented
@rjw1 thank you, have updated code to 16.

2024-06-24 11:27 UTC, rjw1 approved these changes

2024-06-24 12:36 UTC, merged