fix: Remove unused templates and CSS
nationalarchives/ds-caselaw-editor-ui pull request #1490
Opened 2024-06-25 12:27 UTC by adam-murray

## Changes in this PR:
* Reviewed all templates and removed any that are not in use
* Removed associated css

## Jira card / Rollbar error (etc)
https://national-archives.atlassian.net/jira/software/projects/FCL/boards/136?selectedIssue=FCL-128

## Screenshots of UI changes:

### Before

### After

- [ ] Requires env variable(s) to be updated

2024-06-26 09:12 UTC, jacksonj04 requested changes

2024-06-26 09:12 UTC, jacksonj04 commented on ds_caselaw_editor_ui/sass/includes/_browse_by_court.scss
> -.judgment-browse-by-court {
Do we also want to remove the unused `templates/includes/browse_by_court.html`?

2024-06-27 15:28 UTC, dragon-dxw approved these changes

2024-07-01 10:12 UTC, jacksonj04 approved these changes

2024-07-01 10:15 UTC, merged