Add content flags for sensitive and supplemental
nationalarchives/ds-caselaw-editor-ui pull request #16
Opened 2022-03-17 12:26 UTC by LornaHarwood

Added content flags for:

- Case contains sensitive content
- Supplemental documents available

2022-03-17 15:39 UTC, LewisDaleUK approved these changes

2022-03-18 11:45 UTC, lozette requested changes

2022-03-18 11:45 UTC, lozette commented on requirements/base.txt
> +ds-caselaw-marklogic-api-client~=2.0.0
I think this version pin can be removed now

2022-03-21 11:31 UTC, lozette commented on requirements/base.txt
> +ds-caselaw-marklogic-api-client~=2.0.0
```suggestion
ds-caselaw-marklogic-api-client
```

2022-03-21 11:31 UTC, lozette approved these changes

2022-03-21 11:33 UTC, merged