FCL-336 | add extra cases for status colors
nationalarchives/ds-caselaw-editor-ui pull request #1647
Opened 2024-09-25 16:05 UTC by jlhdxw

## Changes in this PR:

Fix for statuses that don't match the judgment format (from the editor metadata)

Separate question on why they don't follow the same format? Couldn't figure out why this might be.

## Jira card / Rollbar error (etc)

https://national-archives.atlassian.net/browse/FCL-336

## Screenshots of UI changes:

### Before

<img width="1264" alt="image" src="https://github.com/user-attachments/assets/73bb8b23-cead-4d67-8043-28b69f87bc54">

### After

<img width="1267" alt="image" src="https://github.com/user-attachments/assets/2872e68e-60f5-4415-ab13-4fff9c31f6ef">

2024-09-25 16:24 UTC, dragon-dxw approved these changes

2024-09-25 17:04 UTC, jacksonj04 requested changes
Super quick tweak to use a constant

2024-09-25 17:04 UTC, jacksonj04 commented on judgments/tests/test_templatetags.py
> +        assert status_tag("In Progress") == "in-progress"
```suggestion
        assert status_tag(DOCUMENT_STATUS_IN_PROGRESS) == "in-progress"
```

2024-09-26 09:53 UTC, jlhdxw commented on judgments/tests/test_templatetags.py
> +        assert status_tag("In Progress") == "in-progress"
Ah sorry - if you check above I'm already doing it. This is testing when it's not the constant (i.e. the state coming from the search rather than the document)

2024-09-26 10:48 UTC, jacksonj04 approved these changes

2024-09-26 10:51 UTC, merged