added two sort values for priority to the sort dropdown
nationalarchives/ds-caselaw-editor-ui pull request #535
Opened 2022-12-07 15:28 UTC by Terry-Price

## Changes in this PR:
Added two extra values to the Sort dropdow for the unpublished judgments screen for Priority:
- Priority - High to Low
- Priority - Low to High

## Trello card / Rollbar error (etc)
https://trello.com/c/JXMNBZTk/77-%F0%9F%91%A9%F0%9F%92%BB-eui-sorting-unpublished-judgments
## Screenshots of UI changes:

### Before
![Screenshot 2022-12-07 at 15 26 47](https://user-images.githubusercontent.com/102584881/206220251-70eed647-72b7-433d-83e1-6c8bd5a62752.png)

### After
![Screenshot 2022-12-07 at 15 26 20](https://user-images.githubusercontent.com/102584881/206220218-62622763-071f-4738-8f7f-243ddc7c4e59.png)

- [ ] Requires env variable(s) to be updated

2022-12-07 15:34 UTC, jacksonj04 requested changes

2022-12-07 15:34 UTC, jacksonj04 commented on ds_caselaw_editor_ui/templates/includes/unpublished_judgments_controls.html
> +        <option value="date" {% if context.order == "date" %}selected='selected'{% endif %}>Priority &ndash; High to Low</option>
`value="date"` means that these two new options will behave exactly the same as "Date received - Oldest"

2022-12-07 16:03 UTC, Terry-Price reviewed
Apologies, I've had to add another commit as I don't have time to find my notes on amending a previous commit.
I have not been given any steer, so I have made these changes, in the logic this works.

2022-12-12 17:09 UTC, timcowlishaw approved these changes

2022-12-13 10:08 UTC, timcowlishaw commented
Commit daf8b4e2632da9a1cb0a781c5b88229ea337fb47 adds the plumbing needed to pass the priority parameter through to the API client and to make sure it persists with pagination, but the marklogic search query still needs some work so that it responds to the 'priority' and '-priority' values and returns an appropriately ordered list. Suggest we wait on merging this until that is done - I'll update the trello ticket at https://trello.com/c/JXMNBZTk/77-%F0%9F%91%A9%F0%9F%92%BB-eui-sorting-priority-for-unpublished-judgments to reflect this.

2023-03-23 11:32 UTC, jacksonj04 commented
Closing as this is now way behind `main` and we've tweaked a lot of how this stuff works, and we'll tweak it again in the near future with filterable lists in EUI.

2023-03-23 11:32 UTC, closed without merging