Add styling to publish page
nationalarchives/ds-caselaw-editor-ui pull request #776
Opened 2023-03-15 13:40 UTC by timcowlishaw

## Changes in this PR:
Adds @Donna-H's styling to @jacksonj04's new publish flow!

A couple of notes:

 - the 'minor issues checklist' is behind the `log_minor_issues_on_publish` feature flag which will need enabling once the required backend work is complete.
 
 - similarly, the 'assign judgment' option in the publish sidebar is behind the `assign_in_publish_sidebar` feature flag, which, again, will need enabling once any required backend work is completed.

## Trello card / Rollbar error (etc)
https://trello.com/c/MRWkx0SG/612-%F0%9F%8E%AB-eui-basic-publish-screen
and 
https://trello.com/c/T3QVjOZS/619-%F0%9F%93%99-eui-basic-successfully-published-screen

## Screenshots of UI changes:

### Before
<img width="1685" alt="Screenshot 2023-03-15 at 14 36 18" src="https://user-images.githubusercontent.com/4279/225326110-8a3640e9-f2f6-434a-8cbf-3dd209b09235.png">

### After
<img width="1685" alt="Screenshot 2023-03-15 at 14 35 58" src="https://user-images.githubusercontent.com/4279/225326163-dfd15640-761f-42b2-86e7-e4763e4aa0c8.png">

2023-03-15 15:54 UTC, timcowlishaw commented
chatted with @Terry-Price @Donna-H  and @jacksonj04 - there's a few outstanding styling tweaks to be made that @Donna-H and I will look at tomorrow.

2023-03-21 16:30 UTC, jacksonj04 requested changes
Really nice work, especially in the refactoring to clean things up. A couple of code tweaks I've flagged where I think things could be deleted, and a couple of whitespace questions (see image below), but other than that it's good to go!

<img width="1536" alt="Screenshot 2023-03-21 at 16 21 18" src="https://user-images.githubusercontent.com/619082/226676400-93c8acc3-da22-42df-9e41-0b286aa77bed.png">

2023-03-21 16:30 UTC, jacksonj04 commented on ds_caselaw_editor_ui/templates/judgment/publish-success.html
> +    <a href="{{ context.judgment.public_uri }}" target="_blank" rel="noopener noreferrer"><br>
I'm not sure this `<br>` semantically belongs within the link, it should probably be on the line above.

2023-03-21 16:30 UTC, jacksonj04 commented on ds_caselaw_editor_ui/sass/includes/publish.scss
This is still called publish.scss, is there a better name for this?

2023-03-21 16:30 UTC, jacksonj04 commented on ds_caselaw_editor_ui/sass/includes/publish.scss
> +.publish-sidebar {
I don't think this class is used any more.

2023-03-21 17:07 UTC, jacksonj04 approved these changes
🎉

2023-03-21 17:11 UTC, merged