Add assignment dropdown to judgment sidebar
nationalarchives/ds-caselaw-editor-ui pull request #841
Opened 2023-04-04 06:04 UTC by timcowlishaw

## Changes in this PR:

This allows editors to reassign judgments on the publish, hold and unhold pages.

It relies on javascript for the behaviour given in the axure prototypes - without JS it will gracefully degrade to a standard form with a submit button.

I've also added test coverage for the assignment button handler logic.

## Trello card / Rollbar error (etc)

https://trello.com/c/T9J35JZF/712-refinement-move-assignment-to-sidebar

## Screenshots of UI changes:
<img width="465" alt="Screenshot 2023-04-04 at 08 02 56" src="https://user-images.githubusercontent.com/4279/229701793-f6cc3524-c079-4b1b-89ef-bf2c96062c6e.png">
<img width="465" alt="Screenshot 2023-04-04 at 08 02 47" src="https://user-images.githubusercontent.com/4279/229701803-e9ddb069-71fa-47b8-a1f0-99dfe7e49ccd.png">

2023-04-05 08:44 UTC, jacksonj04 requested changes
A couple of bits aside from the inline comments:

- Can we move this to the sidebar in all cases, including the edit metadata page, so that it's consistent in all contexts?
- The success message feels very large and looks a lot like a button. We might need to revisit the styling on this.

2023-04-05 08:44 UTC, jacksonj04 commented on ds_caselaw_editor_ui/templates/includes/judgment_sidebar.html
>  {% if feature_flag_assign_in_publish_sidebar %}
This is the wrong flag for this feature.

2023-04-05 08:44 UTC, jacksonj04 commented on ds_caselaw_editor_ui/templates/includes/judgment_sidebar.html
> +      <input type="submit" class="button-cta" name="assign" value="Assign"/>
Can we make `Assign` a locale string and unify the language here and on the judgments list?

2023-04-05 08:44 UTC, jacksonj04 commented on ds_caselaw_editor_ui/static/js/src/components/judgmentSidebar.js
> +    JudgmentSidebar.initAssignForm(element);
Probably a good answer I haven't had enough coffee to grok; what's the logic of having `initOne` instead of `init` just calling `JudgmentSidebar.initAssignForm` directly?

2023-04-05 08:44 UTC, jacksonj04 commented on ds_caselaw_editor_ui/static/js/src/components/judgmentSidebar.js
> +      console.log("changed");
Is this leftover debug code? If not, can it be a more explicit message?

2023-04-05 08:44 UTC, jacksonj04 commented on ds_caselaw_editor_ui/static/js/src/components/judgmentSidebar.js
> +          loading.replaceWith(successMessage);
Could we make this success message disappear after a few seconds? It keeps loitering around looking like an interactive element.

2023-04-05 08:44 UTC, jacksonj04 commented on judgments/tests/test_judgments.py
> +    @patch("judgments.views.button_handlers.api_client")
This feels like a really weird case (I'm guessing legacy behaviour from the judgment list) we should try to get rid of if we can, but probably not in this PR.

2023-04-05 08:44 UTC, jacksonj04 commented on judgments/views/judgment_hold.py
> +                "editors": editors_dict(),
We do this in enough places we should definitely just shove this in a context processor so it's always available.

2023-04-12 08:57 UTC, Terry-Price requested changes
Hey Tim,

Can we change the term from 'judgment' to 'document' This generic term will be better for  none judgment documents.

2023-04-13 12:59 UTC, timcowlishaw commented on ds_caselaw_editor_ui/templates/includes/judgment_sidebar.html
> +      <input type="submit" class="button-cta" name="assign" value="Assign"/>
done!

2023-04-14 15:27 UTC, timcowlishaw commented on ds_caselaw_editor_ui/static/js/src/components/judgmentSidebar.js
> +          loading.replaceWith(successMessage);
done!

2023-04-14 15:28 UTC, timcowlishaw commented on judgments/tests/test_judgments.py
> +    @patch("judgments.views.button_handlers.api_client")
agree, will have a think about how to refactor and do a separate PR

2023-04-14 15:54 UTC, timcowlishaw commented
Hey folks @jacksonj04 @Terry-Price , i've responded to changes requested and left some replies to comments, let me know if you're happy for this to go through!

2023-04-17 16:18 UTC, Terry-Price requested changes
can we change 'judgment' to 'document' on the notification alert.

2023-04-18 16:40 UTC, timcowlishaw commented
> can we change 'judgment' to 'document' on the notification alert.

done, @Terry-Price !

2023-04-18 21:04 UTC, Terry-Price reviewed
i couldnt see the notification message to say document, but assume that’s fine because you mentioned it Tim on here. 

Not for now, but wondered if there is another refactoring card to come out of this for ‘judgment’ class names to be ‘document’ instead. e.g. ‘judgment-cta’ and ‘judgment- sidebar’ and a few others in this space. I may not have recalled the exact class names here, as I can’t see them as I type this.

2023-04-19 09:49 UTC, timcowlishaw commented
> i couldnt see the notification message to say document, but assume that’s fine because you mentioned it Tim on here.
> 
> Not for now, but wondered if there is another refactoring card to come out of this for ‘judgment’ class names to be ‘document’ instead. e.g. ‘judgment-cta’ and ‘judgment- sidebar’ and a few others in this space. I may not have recalled the exact class names here, as I can’t see them as I type this.

aha yep Terry, good point - I think we should also trawl the translations for any reference to judgments too as there's doubtless still some user-facing mentions. Best tackling that all at once though than trying to do it here.

2023-04-19 13:11 UTC, jacksonj04 approved these changes

2023-04-19 13:12 UTC, jacksonj04 commented
I'm happy with this, just needs @Terry-Price to green-light it.

2023-04-19 14:06 UTC, merged